apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  namespace: {{ include "k6-operator.namespace" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http  
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None