apiVersion: v1
kind: Service
metadata:
  name: swift-file-server-api
  annotations:
    linkerd.io/inject: enabled
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: swift-file-server-api