serviceAccount:
  annotations: {}
  create: true

replicaCount: 1
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP

kubeRbacProxy:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi

manager:
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi      

affinity: {}
nodeSelector: {}
tolerations: []

prometheus:
  use: true
  prometheusLabel:
    release: kube-prometheus-stack